stages:
  - package
  - build
  - test
job_package:
  image: maven:3-jdk-8
  stage: package
  script:
    - mvn -f common-lib/pom.xml clean install
    - mvn -f UserS/UserAPP/pom.xml package
    - mvn -f proxy_server/pom.xml package
  artifacts:
    paths:
      - UserS/UserAPP/target/*.jar
      - proxy_server/target/*.jar
    expire_in: 1 week

job_build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - mkdir target
    - cp UserS/UserAPP/target/*.jar target/.
    - cp proxy_server/target/*.jar target/.
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/cpelyon/4ETI-2022-2023/atelier3equipe1/UserS/UserAPP:latest -f UserS/UserAPP/Dockerfile .
    - docker build -t $CI_REGISTRY/cpelyon/4ETI-2022-2023/atelier3equipe1/proxy_server:latest -f proxy_server/Dockerfile .
    - docker push $CI_REGISTRY/cpelyon/4ETI-2022-2023/atelier3equipe1/UserS/UserAPP:latest
    - docker push $CI_REGISTRY/cpelyon/4ETI-2022-2023/atelier3equipe1/proxy_server:latest
  only:
    - master
test:
  stage: test
  image: maven:3-jdk-8
  script: 
    - mvn test
  artifacts:
    reports:
      junit: target/test-results/*.xml
    paths:
      - target/site/jacoco/
