version: "3"
services:
  proxyapp:
    build:
      context: proxy_server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - userapp
    networks:
      - user-network-internal
      - proxy-network-public

  userapp:
    build:
      context: UserS/UserAPP
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/userbd?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=userpassword
    networks:
      - user-network-private
      - user-network-internal

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=userbd
      - MYSQL_USER=username
      - MYSQL_ROOT_PASSWORD=userrootpassword
      - MYSQL_PASSWORD=userpassword
    networks:
      - user-network-private

networks:
  user-network-private:
    internal: true
  user-network-internal:
    internal: true
  proxy-network-public:
